/**
 * AUTO-GENERATED by scripts/extract-cover-colors.js — DO NOT EDIT BY HAND.
 *
 * Per-release colour palettes extracted from each album cover at build time and
 * consumed by composables/useReleaseTheme.ts to paint the cover-driven release
 * page atmosphere. Regenerate with: npm run extract-colors
 *
 * To override a release's palette (e.g. a muddy monochrome cover), set the
 * optional `theme` field on that release in data/musicLibrary.ts — the override
 * always wins over this generated data.
 */

export interface CoverPalette {
  /** Most vibrant dominant colour. */
  primary: string
  /** Second hue-separated colour for the aura mesh. */
  secondary: string
  /** Third accent colour. */
  accent: string
  /** Tinted near-black base for the page background. */
  dark: string
  /** Light tint derived from the primary (highlights / title glow). */
  light: string
  /** De-duplicated colour list (primary first) for the aura blobs. */
  palette: string[]
  /** Whether the cover reads as overall dark. */
  isDark: boolean
  /** Whether the cover is near-monochrome (low saturation) — a good override candidate. */
  isMuted: boolean
}

export const coverColors: Record<string, CoverPalette> = {
  alina: {
    primary: '#7e6058',
    secondary: '#807657',
    accent: '#659e39',
    dark: '#19120f',
    light: '#e2d8d5',
    palette: ['#7e6058', '#807657', '#659e39'],
    isDark: true,
    isMuted: true
  },
  'chorni-ptahy': {
    primary: '#7e5858',
    secondary: '#7e5858',
    accent: '#7e5858',
    dark: '#1b1818',
    light: '#e2d5d5',
    palette: ['#7e5858'],
    isDark: true,
    isMuted: true
  },
  khvyli: {
    primary: '#165fc0',
    secondary: '#61587e',
    accent: '#ae8db0',
    dark: '#101319',
    light: '#c9d9ed',
    palette: ['#165fc0', '#61587e', '#ae8db0'],
    isDark: true,
    isMuted: false
  },
  mania: {
    primary: '#754f87',
    secondary: '#58587e',
    accent: '#4c6d8a',
    dark: '#0e0f13',
    light: '#dfd2e5',
    palette: ['#754f87', '#58587e', '#4c6d8a'],
    isDark: true,
    isMuted: false
  }
}

export const getCoverPalette = (slug: string): CoverPalette | undefined => coverColors[slug]
